showcase.md, templates/monogame/public/main.css, toc.yml
Enabled showcase.md in toc.yml
Moved the existing showcase games per issue  #3 
Adding some supporting css classes
Changed the link to point to the newly created GitHub issue template instead of the Community post
The existing filtering functionality was not moved over with this. Not sure if that is a deal breaker or if there are new plans to do something different.
=> Moving existing Showcase page info to the new site

about.md
The link to Transistor uses an older incorrect URL that leads to a 404 page.  Updated to use the new URL.
=> Fix broken link for Transistor

articles/whats_new.md
This corrects a small typo, avaible -> available, on the “What’s New” documentation page.
=> Fix typo on What’s New page

scripts/game-data.js
Update for #25 .
Beautified the JSON so it has more whitespace and is easier to read.
Cleaned up the escaping \s in the Url fields. Most modern browsers  (Chrome, Firefox, Safari, Edge,) and javascript engines are fine with / now. I tested with a few of these.
Previously this was common practice to avoid script tag injections in html. However, the modern browsers and web standards have other means of prevention. So just having the Urls in the JSON should work fine unless someone is aware of a browser specific issue.
=> Add whitespace to game-data.js cleanup urls

.github/ISSUE_TEMPLATE/01_Showcase_Submission.yml
One more for Issue #3 
Adding an additional image slot to supply the logo.
Added checkboxes to allow for selecting the appropriate tags and platforms. 
Some of this verbiage was taken from the Community post used previously.
Let me know if there are any questions/issues with adding these!
=> Update 01_Showcase_Submission.yml adding Tags/Platforms and Logo

scripts/latest-posts.js
This updates the latest posts script to use the MonoGame community site api instead of the workaround api call used during development. Hopefully there's no CORS issues since it'll be same domain.
=> Changed feed api to use monogame community site

scripts/latest-posts.js
The previous PR updated the URL to use to fetch the latest news feeds, but the endpoints were not updated to the discourse endpoints.
=> Use Discorse API endpoint

showcase/index.md
The microsoft page on [Game Engines](https://dotnet.microsoft.com/en-us/apps/games/engines) built with MS tech contains a broken link to the new monogame [showcase page](https://monogame.net/showcase/).
The issue is with the trailing `/` in the url.
This PR adds a page at `/showcase/` that performs a client-side redirect to the correct route `/showcase`.
TimerBaevRR originally reported this on the MonoGame Discord:  https://discord.com/channels/355231098122272778/1175143217403019365/1183688201051832320
=> Created a redirect from /showcase/ to /showcase

_includes/partials/_footer.njk
Was using site relative path, but community site is hosted at a different subdomain
=> Fixed community link in footer

_includes/partials/_head.njk
This is causing an overwhelming amount of orange in for safari users.  Will need to look into adding it back for social embeds without affecting scrollbars and title window for safari
(screenshot taken from @harry-cpp )
=> Remove `theme` meta tag

content/articles/getting_started/1_setting_up_your_development_environment_unix.md
This is an attempt to address issues such as this one: https://github.com/MonoGame/MonoGame/issues/7982
=> macOS setup documentation

.config/eleventy.config.plugins.js, _data/site.json, content/blog/feed.njk, package-lock.json, package.json
This pull request adds an Atom/RSS feed for the blog page so that users can subscribe to it to receive updates in whatever reader they use when news is posted.  It makes uses of the official 11ty RSS plugin and delivers the feed at the url `https://monogame.net/blog/feed.xml`
I was approached by a community member in discord about adding an RSS feed to the blog. Adding an RSS feed is minimal work and requires no maintenance, it will update itself automatically every time the site is published with changes.
=> Adds an Atom/RSS Feed For Blog

.config/markdownit-plugins/link.js
This PR adds a check in the markdown-it link extension to see if the markdown href begins with `xref:`.  If it does, it will explicitly convert the `xref:` to `/api/` so that the link correctly links to the API page.
After speaking with @SimonDarksideJ this morning, the new documentation they are writing is still using the `xref:` style links for API documentation links.  This PR was made so that documentation can continue to be written the same way without having to go back and update all documentation.
=> Allow `xref:` links in markdown documentation

content/bounties.njk
Link to to the foundation blog category needed a preceding `/` to make the path absolute to the domain and not relative to the page.
=> Fixes blog foundation link on bounty page

_includes/partials/_head.njk
This adds the following meta tag to the `<head>` section of each page
```
<link rel="alternate" type="application/atom+xml" title="MonoGame Blog"  href="/blog/feed.xml" />
```
With the recent atom/rss feed that was added for the blog page, having this tag in the header will allow browsers and extensions that automatically pickup feeds to see it an let the user know there is a feed they can subscribe too.
=> Adds atom/rss feed meta link in page header

.config/dotnet-tools.json, package-lock.json
This is in regards to issue #58 
A new docfx version with the fix for their issue [9618](https://github.com/dotnet/docfx/issues/9618) (as reported by Aristurtle, thank you!) has been released. 
In my test app the Ubuntu runner was able to produce the 460ish api docs when using the newest version of docfx.
=> Bump docfx version to fix api doc issue

.github/workflows/main.yaml
We need to upgrade the .NET version now that we upgraded MonoGame.
@AristurtleDev Do we still need v6 or v7? It seems that docfx should work on .NET 8 too and we only need that version.
=> Update dotnet version

documentation/articles/getting_started/1_setting_up_your_development_environment_windows.md
This is a documentation fix for the Getting Started guide on the website.
https://monogame.net/articles/getting_started/1_setting_up_your_development_environment_windows.html
**Issue:**  
The command in the Getting Started section for installing MonoGame templates for .NET does not work.
```sh
dotnet new install MonoGame.Templates.CSharp
```
Instead it has to be:
```sh
dotnet new --install MonoGame.Templates.CSharp
```
The latter is consistent with other places in the documentation and allowed me to install MonoGame and use it in Jetbrains Rider.
=> [Documentation] Fix instructions for installing MonoGame Templates

documentation/templates/monogame/conceptual.extension.js
This PR adjusts changes made in PR #118 so that instead of getting the `title` and `description` from the first `<h1>` and `<p>` tags on the page, it instead will use the `title` and `description` frontmatter to automatically inject the `<h1>` and `<p>` tag into the page.
An additional frontmatter property has been added called `descriptionStyle` which can be used to style the `<p>` tag using a css class.  By default it will use `text-secondary`.
- Adjusting the title
https://github.com/MonoGame/monogame.github.io/assets/103014489/9e7d4bf3-a95a-42cb-9270-976742055bcb
- Adjusting the description
https://github.com/MonoGame/monogame.github.io/assets/103014489/49fca355-8eb6-4012-bb36-3439205d2de2
- Adjusting the description style
https://github.com/MonoGame/monogame.github.io/assets/103014489 …
=> Use FrontMatter For Autotitle And Descritpion

website/content/index.njk
This updates the getting started link to point to the new docs.monogame.net subdomain so there's no 404
=> Update getting started link

website/content/index.njk
just a notice a small typographical error or a simple mistake in writing, if you go to the index.njk for the web page, we will see under Open-Source -> contribute, an extra "is".
it is really not much of an issue, just wanted to help abit
=> Update index.njk (typographical error or a simple mistake in writing)

website/.config/eleventy.config.passthrough.js, website/content/public/downloads/winesetup/net6_mgfxc_wine_setup.sh, website/content/public/downloads/winesetup/net8_mgfxc_wine_setup.sh
This PR adds the mgfx_wine_setup.sh scripts to the website.  This was done following the suggestion from a conversation with @harry-cpp.  Both scripts have been added to the website, one for the current stable MonoGame 3.8.1.303 (`net6_mgfxc_wine_setup.sh`) and one for the current develop builds (`net8_mgfxc_wine_setup.sh`).
Once merged they will be available at
- https://monogame.net/downloads/net6_mgfxc_wine_setup.sh
- https://monogame.net/downloads/net8_mgfxc_wine_setup.sh
After merge, documentation will need to be updated to use the new urls for the wget download command
The reason for doing this is that at the current moment there is no way for Linux or Mac users to actually do the wine setup correctly.  The current documentation points them to download the wine setup script from the …
=> Add wine setup scripts to site

website/content/public/downloads/winesetup/net8_mgfxc_wine_setup.sh
Some issues with the install script caused errors on macos.  The default macos `grep` does not support the -P perl flag.  So use a basic regex instead.
We are trying to run `wine` in one part of the script, which will fail on M* Apple Macs because it is a 32bit executable. 
Also upgade to .net 8.0.401
=> Fix MacOS net8_mgfxc_wine_setup.sh

CONTRIBUTING.md, website/content/about.njk
This is to resolve issue [#8533](https://github.com/MonoGame/MonoGame/issues/8533) that was submitted on the main MonoGame repo, but is actually for this bug on the website.
I also updated the link and text on the CONTRIBUTING.md as it mentioned this being the documentation repo and had an old link that 404s. With the documentation site and the website being separate I felt the text should probably be changed. Let me know if there are any concerns/issues with the change I made!
=> Updated broken links and contributing link and text

website/_includes/partials/_footer.njk, website/content/about.njk, website/content/donate.njk, website/content/index.njk
=> Add non-profit info

website/.config/markdownit-plugins/admonitions.js
It was possible for admonitions to be duplicated when placed after a list.
From what I can tell, the alt options weren't needed. It's still possible to have an admonition inside of a list without it.
=> Fixed double admonitions

website/content/donate.njk, website/content/public/js/patreon.js
This is how it looks now:
Also added Re-logic's monthly donation to the total for public accuracy.
=> GitHub Sponsors Link

website/_data/foundation.json, website/_includes/partials/_footer.njk
Fixed a broken link on about and updated the footer to include the current year in the copyright.
=> Fix broken link and update footer year

website/_includes/partials/_blog_footer.njk, website/content/blog/2024-12-01-a-year-in-review.md, website/content/bounties.njk, website/content/index.njk
It's capitalized in other places on the site, and in official GitHub branding, so let's make it consistent everywhere :)
=> Capitalize the "H" in "GitHub"

website/content/resources.njk
If a resource listed has more than three tags, then the tags wrap around and can get crowded. 
Here is an example, with 7 tags
This PR adds logic to the `resource.njk` template to
- When a resource contains more than 3 tags, a 4th element is displayed with just the additional number of tags (e.g. if a resource has 4 tags, the element will say "+1"
- When the 4th element is hovered, a tool tip is enabled that lists the additional tags
Here is a video example of this in action
https://github.com/user-attachments/assets/161eb4b7-708f-4d1c-90c3-bef66f3fa189
=> Multiple resource tags

website/content/public/downloads/winesetup/net6_mgfxc_wine_setup.sh, website/content/public/downloads/winesetup/net8_mgfxc_wine_setup.sh, website/content/public/downloads/winesetup/net9_mgfxc_wine_setup.sh
For dotnet 9 we don't want to create symlinks as we can fix the WineHelper.
=> Fix wine setup scripts

website/content/bounties.njk
We should only require an NDA if the bounty relates to closed source platforms. For bounties dealing with the open source repo the contributor agreement should be enough.
=> Loosen the NDA requirements

website/content/public/css/main.css
This reduces the height of the hero carousel on the home page by 20% so that viewers can see there is move below it and to scroll down.
Reference:
- PR #237 
- Closes #239
=> Reduce the size of the hero carousel by 20%

website/content/public/js/carousel.js
The carousel was always showing 1 of 4 different games first always.  This fixes it so the order is always fully random.
=> Fixed carousel randomization bugs.
