MonoGame/monogame.github.io

.github/ISSUE_TEMPLATE/01_Showcase_Submission.yml, .github/ISSUE_TEMPLATE/config.yml
This PR adds the Showcase Submission template for issue #3
=> Add Showcase Submission template

.github/ISSUE_TEMPLATE/02_Documentation_Issue.yml
This PR adds a Documentation Issue template to the Issue Templates.
=> Created Documentation Issue Template

docfx.json
Quick fix to use the correct image for the OpenGraph and Twitter Card images
=> Use correct image for OpenGraph

scripts/showcase-filters.js
Issue #43 
Adding improvement to the seed value per request/suggestion from @tomspilman 
This fixes the random ordering repeating on the same hour each day issue.
=> Improve showcase randomness across time

api/index.md, templates/monogame/ManagedReference.extension.js, templates/monogame/layout/_master.tmpl
=> Use container-fluid for API pages

content/about.njk
Some text got accidentally copied into the board members intro. Cleaned that up here.
=> Cleanup text on About

content/articles/content_pipeline/adding_ttf_fonts.md, content/articles/content_pipeline/custom_effects.md, content/articles/content_pipeline/using_mgcb_editor.md, content/articles/content_pipeline/why_content_pipeline.md, content/articles/getting_started/2_creating_a_new_project_netcore.md, content/articles/getting_started/4_adding_content.md, content/articles/getting_started/5_adding_basic_code.md, content/articles/migrate_xna.md, content/articles/tools/mgcb.md, package-lock.json
There are a number of linking issues with cross folder md files and xref's not being able to hit the generated api documentation.
I have fixed all of them that I have found in this PR.
=> Fix various relative path issues

content/blog/2023-10-24-meeting.md, content/blog/2023-11-15-meeting.md, content/blog/2023-11-22-meeting.md, content/blog/2023-12-29-website-refresh.md, content/blog/2024-01-10-meeting.md
Re-releasing the Meeting notes for 2024,
Also minor gramatical and spelling fixes for previous articles
=> Meeting notes for 2024-01-10

content/donate.njk
We crafted a new message to help encourage donations to the project.
=> New donation message.

_includes/partials/_head.njk
Adds the google analytics script to the `<head>` section.
=> Add google analytics script

website/_includes/partials/_footer.njk
Links in footer needed to be updated due to the split in the website and docs repos
=> Update footer links

website/content/public/css/main.css
Adds the styling for block quotes sections produced from markdown
=> Fix blockquote styling

website/content/index.njk
- Fixed wording a bit with the "MG is free" text.
- Linked console access doc.
- Linked donation page from donation ask.
=> Homepage Fixes

website/content/redirects.md
Ensures that the redirects are put in a directory
=> Fix redirect template

website/_data/timeline.json
Add 3.8.2 Release to timeline.
=> Add 3.8.2 Release to timeline

website/content/public/downloads/winesetup/net8_mgfxc_wine_setup.sh, website/content/public/downloads/winesetup/net9_mgfxc_wine_setup.sh
Related: https://github.com/dotnet/core/issues/9671
=> Update dotnetcli domain

website/content/public/css/main.css, website/content/public/css/main.lg.css, website/content/resources.njk
Adds styling for resource page
| Light Mode | Dark Mode |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/7864f469-32a2-4a74-88bc-f6c6649d64a4) |  ![image](https://github.com/user-attachments/assets/09c9c1d2-1908-4298-b1be-691cbad32ce6) |
=> Add style for resource page

website/_data/resources.json
Hi! I submitted MLEM.Ui as a resource before there was a Ui tag in the resources section, and I wanted MLEM.Ui to be a part of it too. I hope doing it as a pull request like this is okay!
Thanks so much for creating this resources section, it'll be a huge help to new MG users and library/tool creators looking for more users :)
=> Also add MLEM resource to ui tag

website/_data/timeline.json
Adding the newest release to the timeline.
=> Update timeline to include 3.8.4 release

website/_data/resources.json
Ink is a powerful Narrative Scripting runtime (and editor) for games.
https://www.inklestudios.com/ink/
=> Add Ink Narrative Scripting

FetchGHSponsors/action.yml
I was not getting cents back from the GH Sponsors fetch.
=> GH Sponsors Bug Fix

package-lock.json, website/content/index.njk
Made Getting Started Link To Document Homepage (https://docs.monogame.net/)
=> Updated Getting Started
